/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
	const BContextMenu: (typeof import('./src/components/composable/context-menu/index'))['BContextMenu']
}
